class Pokemon {
  final int id;
  final String name;
  final String type;
  final String description;
  final String emoji;
  final Map<String, int> stats;
  final String role;
  final String ability;
  final String weakness;
  final String evolution;
  final List<String> partners;

  Pokemon({
    required this.id,
    required this.name,
    required this.type,
    required this.description,
    required this.emoji,
    required this.stats,
    required this.role,
    required this.ability,
    required this.weakness,
    required this.evolution,
    required this.partners,
  });

  String get assetPath => 'images/${name.toLowerCase().replaceAll(' ', '')}.png';
}

final List<Pokemon> pokemonData = [
  Pokemon(
    id: 1,
    name: 'Bulbasaur',
    type: 'Grass / Poison',
    emoji: '🌱',
    description:
        'Bulbasaur adalah Pokémon yang mengandalkan keseimbangan antara offense dan defense. Tanaman di punggungnya menyimpan energi matahari untuk memperkuat serangan.',
    stats: {
      'HP': 45,
      'Atk': 49,
      'Def': 49,
      'Sp. Atk': 65,
      'Sp. Def': 65,
      'Speed': 45,
    },
    role: 'Support / Tank awal game',
    ability: 'Overgrow',
    weakness: 'Fire, Ice, Flying, Psychic',
    evolution: 'Ivysaur (Lv.16)',
    partners: ['Pikachu', 'Growlithe', 'Geodude'],
  ),
  Pokemon(
    id: 4,
    name: 'Charizard',
    type: 'Fire / Flying',
    emoji: '🔥🐉',
    description:
        'Charizard adalah attacker cepat dengan damage tinggi, terutama di Special Attack. Sangat berbahaya tapi punya kelemahan besar terhadap Rock-type.',
    stats: {
      'HP': 78,
      'Atk': 84,
      'Def': 78,
      'Sp. Atk': 109,
      'Sp. Def': 85,
      'Speed': 100,
    },
    role: 'Special Attacker / Sweeper',
    ability: 'Blaze',
    weakness: 'Rock (x4), Water, Electric',
    evolution: 'Final',
    partners: ['Blastoise', 'Jolteon', 'Excadrill'],
  ),
  Pokemon(
    id: 7,
    name: 'Blastoise',
    type: 'Water',
    emoji: '💧',
    description:
        'Blastoise adalah tank kuat dengan defense tinggi. Cocok untuk bertahan lama dan memberikan tekanan stabil.',
    stats: {
      'HP': 79,
      'Atk': 83,
      'Def': 100,
      'Sp. Atk': 85,
      'Sp. Def': 105,
      'Speed': 78,
    },
    role: 'Tank / Defensive Support',
    ability: 'Torrent',
    weakness: 'Electric, Grass',
    evolution: 'Final',
    partners: ['Venusaur', 'Raichu', 'Dragonite'],
  ),
  Pokemon(
    id: 25,
    name: 'Pikachu',
    type: 'Electric',
    emoji: '⚡',
    description:
        'Pikachu adalah Pokémon cepat dengan serangan listrik yang efektif melawan Water dan Flying. Tapi cukup rapuh.',
    stats: {
      'HP': 35,
      'Atk': 55,
      'Def': 40,
      'Sp. Atk': 50,
      'Sp. Def': 50,
      'Speed': 90,
    },
    role: 'Fast Attacker / Utility',
    ability: 'Static',
    weakness: 'Ground',
    evolution: '',
    partners: ['Charizard', 'Bulbasaur', 'Gyarados'],
  ),
  Pokemon(
    id: 94,
    name: 'Gengar',
    type: 'Ghost / Poison',
    emoji: '👻',
    description:
        'Gengar adalah glass cannon dengan Special Attack tinggi dan kecepatan luar biasa. Cocok untuk menghabisi lawan dengan cepat.',
    stats: {
      'HP': 60,
      'Atk': 65,
      'Def': 60,
      'Sp. Atk': 130,
      'Sp. Def': 75,
      'Speed': 110,
    },
    role: 'Special Sweeper',
    ability: 'Cursed Body',
    weakness: 'Ghost, Dark, Psychic',
    evolution: 'Final',
    partners: ['Snorlax', 'Tyranitar', 'Alakazam'],
  ),
  Pokemon(
    id: 149,
    name: 'Dragonite',
    type: 'Dragon / Flying',
    emoji: '🐉',
    description:
        'Dragonite adalah pseudo-legendary dengan stat tinggi di hampir semua aspek. Walau terlihat ramah, dia sangat kuat di battle.',
    stats: {
      'HP': 91,
      'Atk': 134,
      'Def': 95,
      'Sp. Atk': 100,
      'Sp. Def': 100,
      'Speed': 80,
    },
    role: 'Physical Sweeper / All-rounder',
    ability: 'Inner Focus',
    weakness: 'Ice (x4), Rock, Dragon, Fairy',
    evolution: 'Final',
    partners: ['Heatran', 'Magnezone', 'Blastoise'],
  ),
  Pokemon(
    id: 143,
    name: 'Snorlax',
    type: 'Normal',
    emoji: '😴',
    description:
        'Snorlax adalah tank dengan HP besar. Sulit dikalahkan dan bisa jadi tembok tim.',
    stats: {
      'HP': 160,
      'Atk': 110,
      'Def': 65,
      'Sp. Def': 110,
      'Speed': 30,
    },
    role: 'Tank / Wall',
    ability: 'Thick Fat',
    weakness: 'Fighting',
    evolution: 'Final',
    partners: ['Gengar', 'Togekiss', 'Excadrill'],
  ),
  Pokemon(
    id: 133,
    name: 'Eevee',
    type: 'Normal',
    emoji: '🧬',
    description:
        'Eevee unik karena punya banyak evolusi (Eeveelutions). Fleksibel sesuai kebutuhan tim.',
    stats: {
      'HP': 55,
      'Atk': 55,
      'Def': 50,
      'Sp. Atk': 45,
      'Sp. Def': 65,
      'Speed': 55,
    },
    role: 'Flexible / Support',
    ability: 'Adaptability',
    weakness: 'Fighting',
    evolution: 'Multiple (Jolteon, Vaporeon, dll)',
    partners: ['Jolteon', 'Vaporeon', 'Flareon'],
  ),
  Pokemon(
    id: 134,
    name: 'Vaporeon',
    type: 'Water',
    emoji: '💧',
    description:
        'Tank spesial dengan HP besar dan sustain tinggi. Eeveelution yang sangat kuat untuk defense.',
    stats: {
      'HP': 130,
      'Atk': 65,
      'Def': 60,
      'Sp. Atk': 110,
      'Sp. Def': 95,
      'Speed': 65,
    },
    role: 'Special Tank / Support',
    ability: 'Water Absorb',
    weakness: 'Electric, Grass',
    evolution: 'Final (dari Eevee)',
    partners: ['Jolteon', 'Flareon', 'Ferrothorn'],
  ),
  Pokemon(
    id: 135,
    name: 'Jolteon',
    type: 'Electric',
    emoji: '⚡',
    description:
        'Salah satu Pokémon tercepat. Cocok untuk strike cepat dan special attack yang tinggi.',
    stats: {
      'HP': 65,
      'Atk': 65,
      'Def': 60,
      'Sp. Atk': 110,
      'Sp. Def': 95,
      'Speed': 130,
    },
    role: 'Fast Special Sweeper',
    ability: 'Volt Absorb',
    weakness: 'Ground',
    evolution: 'Final (dari Eevee)',
    partners: ['Vaporeon', 'Charizard', 'Scizor'],
  ),
  Pokemon(
    id: 136,
    name: 'Flareon',
    type: 'Fire',
    emoji: '🔥',
    description:
        'Damage fisik tinggi tapi agak lambat. Eeveelution dengan attack yang paling besar.',
    stats: {
      'HP': 65,
      'Atk': 130,
      'Def': 60,
      'Sp. Def': 110,
      'Speed': 65,
    },
    role: 'Physical Attacker',
    ability: 'Flash Fire',
    weakness: 'Water, Ground, Rock',
    evolution: 'Final (dari Eevee)',
    partners: ['Jolteon', 'Vaporeon', 'Tyranitar'],
  ),
  Pokemon(
    id: 445,
    name: 'Lucario',
    type: 'Fighting / Steel',
    emoji: '🐺',
    description:
        'Fighter dengan aura power, bisa mixed attacker yang powerful dan cepat.',
    stats: {
      'HP': 70,
      'Atk': 110,
      'Def': 70,
      'Sp. Atk': 115,
      'Speed': 90,
    },
    role: 'Mixed Sweeper',
    ability: 'Steadfast',
    weakness: 'Fire, Ground, Fighting',
    evolution: 'Final',
    partners: ['Gengar', 'Garchomp', 'Rotom-Wash'],
  ),
  Pokemon(
    id: 658,
    name: 'Greninja',
    type: 'Water / Dark',
    emoji: '🥷',
    description:
        'Ninja Pokémon super cepat dengan ability unik (Protean). Bisa berubah tipe sesuai move.',
    stats: {
      'HP': 72,
      'Atk': 95,
      'Def': 67,
      'Sp. Atk': 103,
      'Sp. Def': 71,
      'Speed': 122,
    },
    role: 'Speed Sweeper',
    ability: 'Protean',
    weakness: 'Electric, Grass, Fighting, Ghost',
    evolution: 'Final',
    partners: ['Talonflame', 'Aegislash', 'Garchomp'],
  ),
  Pokemon(
    id: 68,
    name: 'Machamp',
    type: 'Fighting',
    emoji: '💪',
    description:
        'Petarung kuat dengan 4 tangan. Physical attacker yang sangat dangerous.',
    stats: {
      'HP': 90,
      'Atk': 130,
      'Def': 80,
      'Sp. Atk': 65,
      'Sp. Def': 85,
      'Speed': 55,
    },
    role: 'Physical Attacker',
    ability: 'Guts',
    weakness: 'Flying, Psychic, Fairy',
    evolution: 'Final',
    partners: ['Alakazam', 'Gengar', 'Snorlax'],
  ),
  Pokemon(
    id: 65,
    name: 'Alakazam',
    type: 'Psychic',
    emoji: '🧠',
    description:
        'Glass cannon dengan kecerdasan tinggi dan special attack yang luar biasa.',
    stats: {
      'HP': 55,
      'Atk': 50,
      'Def': 45,
      'Sp. Atk': 135,
      'Sp. Def': 95,
      'Speed': 120,
    },
    role: 'Special Sweeper',
    ability: 'Magic Guard',
    weakness: 'Bug, Ghost, Dark',
    evolution: 'Final',
    partners: ['Machamp', 'Gengar', 'Scizor'],
  ),
  Pokemon(
    id: 130,
    name: 'Gyarados',
    type: 'Water / Flying',
    emoji: '🐉',
    description:
        'Agresif dan kuat secara fisik. Evolusi dari Magikarp yang sangat powerful.',
    stats: {
      'HP': 95,
      'Atk': 125,
      'Def': 79,
      'Sp. Atk': 60,
      'Sp. Def': 100,
      'Speed': 81,
    },
    role: 'Physical Sweeper',
    ability: 'Intimidate',
    weakness: 'Electric, Rock',
    evolution: 'Final',
    partners: ['Jolteon', 'Garchomp', 'Ferrothorn'],
  ),
  Pokemon(
    id: 248,
    name: 'Tyranitar',
    type: 'Rock / Dark',
    emoji: '🪨',
    description:
        'Tank + attacker kuat, summon sandstorm. Salah satu Pokémon terkuat generation 2.',
    stats: {
      'HP': 100,
      'Atk': 134,
      'Def': 110,
      'Sp. Atk': 95,
      'Sp. Def': 100,
      'Speed': 61,
    },
    role: 'Tank / Sweeper',
    ability: 'Sand Stream',
    weakness: 'Water, Grass, Fighting, Ground, Steel, Fairy',
    evolution: 'Final',
    partners: ['Excadrill', 'Garchomp', 'Rotom-Wash'],
  ),
];
